// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package ganrag_user

import (
	"time"
)

const TableNameRefreshToken = "refresh_tokens"

// RefreshToken mapped from table <refresh_tokens>
type RefreshToken struct {
	ID        int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID    int64      `gorm:"column:user_id;not null" json:"user_id"`
	TokenHash string     `gorm:"column:token_hash;not null" json:"token_hash"`
	ExpiresAt time.Time  `gorm:"column:expires_at;not null" json:"expires_at"`
	RevokedAt *time.Time `gorm:"column:revoked_at" json:"revoked_at"`
	CreatedAt time.Time  `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName RefreshToken's table name
func (*RefreshToken) TableName() string {
	return TableNameRefreshToken
}
