// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package ganrag_user

import (
	"time"
)

const TableNameUserFollow = "user_follows"

// UserFollow mapped from table <user_follows>
type UserFollow struct {
	FollowerID int64     `gorm:"column:follower_id;primaryKey" json:"follower_id"`
	FolloweeID int64     `gorm:"column:followee_id;primaryKey" json:"followee_id"`
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName UserFollow's table name
func (*UserFollow) TableName() string {
	return TableNameUserFollow
}
