// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package ganrag_user

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/gangantongxue/GanRAG/pkg/db/model/ganrag_user"
)

func newRefreshToken(db *gorm.DB, opts ...gen.DOOption) refreshToken {
	_refreshToken := refreshToken{}

	_refreshToken.refreshTokenDo.UseDB(db, opts...)
	_refreshToken.refreshTokenDo.UseModel(&ganrag_user.RefreshToken{})

	tableName := _refreshToken.refreshTokenDo.TableName()
	_refreshToken.ALL = field.NewAsterisk(tableName)
	_refreshToken.ID = field.NewInt64(tableName, "id")
	_refreshToken.UserID = field.NewInt64(tableName, "user_id")
	_refreshToken.TokenHash = field.NewString(tableName, "token_hash")
	_refreshToken.ExpiresAt = field.NewTime(tableName, "expires_at")
	_refreshToken.RevokedAt = field.NewTime(tableName, "revoked_at")
	_refreshToken.CreatedAt = field.NewTime(tableName, "created_at")

	_refreshToken.fillFieldMap()

	return _refreshToken
}

type refreshToken struct {
	refreshTokenDo refreshTokenDo

	ALL       field.Asterisk
	ID        field.Int64
	UserID    field.Int64
	TokenHash field.String
	ExpiresAt field.Time
	RevokedAt field.Time
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (r refreshToken) Table(newTableName string) *refreshToken {
	r.refreshTokenDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r refreshToken) As(alias string) *refreshToken {
	r.refreshTokenDo.DO = *(r.refreshTokenDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *refreshToken) updateTableName(table string) *refreshToken {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.UserID = field.NewInt64(table, "user_id")
	r.TokenHash = field.NewString(table, "token_hash")
	r.ExpiresAt = field.NewTime(table, "expires_at")
	r.RevokedAt = field.NewTime(table, "revoked_at")
	r.CreatedAt = field.NewTime(table, "created_at")

	r.fillFieldMap()

	return r
}

func (r *refreshToken) WithContext(ctx context.Context) *refreshTokenDo {
	return r.refreshTokenDo.WithContext(ctx)
}

func (r refreshToken) TableName() string { return r.refreshTokenDo.TableName() }

func (r refreshToken) Alias() string { return r.refreshTokenDo.Alias() }

func (r refreshToken) Columns(cols ...field.Expr) gen.Columns {
	return r.refreshTokenDo.Columns(cols...)
}

func (r *refreshToken) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *refreshToken) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 6)
	r.fieldMap["id"] = r.ID
	r.fieldMap["user_id"] = r.UserID
	r.fieldMap["token_hash"] = r.TokenHash
	r.fieldMap["expires_at"] = r.ExpiresAt
	r.fieldMap["revoked_at"] = r.RevokedAt
	r.fieldMap["created_at"] = r.CreatedAt
}

func (r refreshToken) clone(db *gorm.DB) refreshToken {
	r.refreshTokenDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r refreshToken) replaceDB(db *gorm.DB) refreshToken {
	r.refreshTokenDo.ReplaceDB(db)
	return r
}

type refreshTokenDo struct{ gen.DO }

func (r refreshTokenDo) Debug() *refreshTokenDo {
	return r.withDO(r.DO.Debug())
}

func (r refreshTokenDo) WithContext(ctx context.Context) *refreshTokenDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r refreshTokenDo) ReadDB() *refreshTokenDo {
	return r.Clauses(dbresolver.Read)
}

func (r refreshTokenDo) WriteDB() *refreshTokenDo {
	return r.Clauses(dbresolver.Write)
}

func (r refreshTokenDo) Session(config *gorm.Session) *refreshTokenDo {
	return r.withDO(r.DO.Session(config))
}

func (r refreshTokenDo) Clauses(conds ...clause.Expression) *refreshTokenDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r refreshTokenDo) Returning(value interface{}, columns ...string) *refreshTokenDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r refreshTokenDo) Not(conds ...gen.Condition) *refreshTokenDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r refreshTokenDo) Or(conds ...gen.Condition) *refreshTokenDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r refreshTokenDo) Select(conds ...field.Expr) *refreshTokenDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r refreshTokenDo) Where(conds ...gen.Condition) *refreshTokenDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r refreshTokenDo) Order(conds ...field.Expr) *refreshTokenDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r refreshTokenDo) Distinct(cols ...field.Expr) *refreshTokenDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r refreshTokenDo) Omit(cols ...field.Expr) *refreshTokenDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r refreshTokenDo) Join(table schema.Tabler, on ...field.Expr) *refreshTokenDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r refreshTokenDo) LeftJoin(table schema.Tabler, on ...field.Expr) *refreshTokenDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r refreshTokenDo) RightJoin(table schema.Tabler, on ...field.Expr) *refreshTokenDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r refreshTokenDo) Group(cols ...field.Expr) *refreshTokenDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r refreshTokenDo) Having(conds ...gen.Condition) *refreshTokenDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r refreshTokenDo) Limit(limit int) *refreshTokenDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r refreshTokenDo) Offset(offset int) *refreshTokenDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r refreshTokenDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *refreshTokenDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r refreshTokenDo) Unscoped() *refreshTokenDo {
	return r.withDO(r.DO.Unscoped())
}

func (r refreshTokenDo) Create(values ...*ganrag_user.RefreshToken) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r refreshTokenDo) CreateInBatches(values []*ganrag_user.RefreshToken, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r refreshTokenDo) Save(values ...*ganrag_user.RefreshToken) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r refreshTokenDo) First() (*ganrag_user.RefreshToken, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*ganrag_user.RefreshToken), nil
	}
}

func (r refreshTokenDo) Take() (*ganrag_user.RefreshToken, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*ganrag_user.RefreshToken), nil
	}
}

func (r refreshTokenDo) Last() (*ganrag_user.RefreshToken, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*ganrag_user.RefreshToken), nil
	}
}

func (r refreshTokenDo) Find() ([]*ganrag_user.RefreshToken, error) {
	result, err := r.DO.Find()
	return result.([]*ganrag_user.RefreshToken), err
}

func (r refreshTokenDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*ganrag_user.RefreshToken, err error) {
	buf := make([]*ganrag_user.RefreshToken, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r refreshTokenDo) FindInBatches(result *[]*ganrag_user.RefreshToken, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r refreshTokenDo) Attrs(attrs ...field.AssignExpr) *refreshTokenDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r refreshTokenDo) Assign(attrs ...field.AssignExpr) *refreshTokenDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r refreshTokenDo) Joins(fields ...field.RelationField) *refreshTokenDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r refreshTokenDo) Preload(fields ...field.RelationField) *refreshTokenDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r refreshTokenDo) FirstOrInit() (*ganrag_user.RefreshToken, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*ganrag_user.RefreshToken), nil
	}
}

func (r refreshTokenDo) FirstOrCreate() (*ganrag_user.RefreshToken, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*ganrag_user.RefreshToken), nil
	}
}

func (r refreshTokenDo) FindByPage(offset int, limit int) (result []*ganrag_user.RefreshToken, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r refreshTokenDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r refreshTokenDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r refreshTokenDo) Delete(models ...*ganrag_user.RefreshToken) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *refreshTokenDo) withDO(do gen.Dao) *refreshTokenDo {
	r.DO = *do.(*gen.DO)
	return r
}
